version: '3.9'

services:
  auth:
    build: ./auth
    image: auth:latest
    restart: unless-stopped
    container_name: auth

    ports:
      - 8081:8081

    volumes:
      - ./.env:/app/.env:ro

    command: uvicorn main:app --host 0.0.0.0 --port 8081

  budget:
    build: ./budget
    image: budget:latest
    restart: unless-stopped
    container_name: budget

    ports:
      - 8000:8000

    volumes:
      - ./.env:/app/.env:ro

    command: uvicorn main:app --host 0.0.0.0 --port 8000

    depends_on:
      - auth

  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
